# Form implementation generated from reading ui file 'authentication.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(539, 239)
        Dialog.setMinimumSize(QtCore.QSize(539, 239))
        Dialog.setMaximumSize(QtCore.QSize(539, 239))
        Dialog.setStyleSheet("")
        self.MainstackedWidget = QtWidgets.QStackedWidget(Dialog)
        self.MainstackedWidget.setGeometry(QtCore.QRect(-1, 40, 541, 191))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.MainstackedWidget.setFont(font)
        self.MainstackedWidget.setStyleSheet("background-color: rgb(56, 58, 89);\n"
"\n"
"\n"
"")
        self.MainstackedWidget.setObjectName("MainstackedWidget")
        self.login = QtWidgets.QWidget()
        self.login.setObjectName("login")
        self.unlock_btn = QtWidgets.QPushButton(self.login)
        self.unlock_btn.setEnabled(True)
        self.unlock_btn.setGeometry(QtCore.QRect(240, 130, 75, 24))
        self.unlock_btn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.unlock_btn.setStyleSheet("QPushButton{\n"
"  border: 1.5px solid white;\n"
"  border-radius: 12px;\n"
"  padding: 5px;\n"
"  color: rgb(255, 255, 255)\n"
"}\n"
"QPushButton:hover{\n"
"  background-color: rgb(199, 199, 199);  \n"
"}\n"
"QPushButton:disabled{\n"
"  color: rgb(199, 199, 199);  \n"
"}")
        self.unlock_btn.setObjectName("unlock_btn")
        self.label_3 = QtWidgets.QLabel(self.login)
        self.label_3.setGeometry(QtCore.QRect(0, 30, 541, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(255, 255, 255)")
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.master_password_single_user = QtWidgets.QLineEdit(self.login)
        self.master_password_single_user.setGeometry(QtCore.QRect(150, 70, 241, 21))
        self.master_password_single_user.setStyleSheet("QLineEdit{\n"
"color: rgb(255, 255, 255)\n"
"}\n"
"QLineEdit:disabled{\n"
"  color: rgb(199, 199, 199);  \n"
"}")
        self.master_password_single_user.setText("")
        self.master_password_single_user.setEchoMode(QtWidgets.QLineEdit.EchoMode.PasswordEchoOnEdit)
        self.master_password_single_user.setClearButtonEnabled(False)
        self.master_password_single_user.setObjectName("master_password_single_user")
        self.forgot_password = QtWidgets.QPushButton(self.login)
        self.forgot_password.setEnabled(True)
        self.forgot_password.setGeometry(QtCore.QRect(200, 160, 161, 31))
        self.forgot_password.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.forgot_password.setStyleSheet("QPushButton{\n"
"  border: none;\n"
"  border-radius: 12px;\n"
"  padding: 5px;\n"
"  color: rgb(255, 255, 255)\n"
"}\n"
"QPushButton:hover{\n"
"  color: rgb(199, 199, 199);  \n"
"}\n"
"QPushButton:disabled{\n"
"  color: rgb(199, 199, 199);  \n"
"}")
        self.forgot_password.setObjectName("forgot_password")
        self.stackedWidgetmp = QtWidgets.QStackedWidget(self.login)
        self.stackedWidgetmp.setGeometry(QtCore.QRect(150, 90, 241, 31))
        self.stackedWidgetmp.setObjectName("stackedWidgetmp")
        self.wrongpass_enter = QtWidgets.QWidget()
        self.wrongpass_enter.setObjectName("wrongpass_enter")
        self.label_8 = QtWidgets.QLabel(self.wrongpass_enter)
        self.label_8.setGeometry(QtCore.QRect(80, 10, 141, 16))
        self.label_8.setStyleSheet("color: rgb(255, 0, 0)\n"
"")
        self.label_8.setObjectName("label_8")
        self.stackedWidgetmp.addWidget(self.wrongpass_enter)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.stackedWidgetmp.addWidget(self.page_2)
        self.MainstackedWidget.addWidget(self.login)
        self.newuser = QtWidgets.QWidget()
        self.newuser.setObjectName("newuser")
        self.label_5 = QtWidgets.QLabel(self.newuser)
        self.label_5.setGeometry(QtCore.QRect(120, 60, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgb(255, 255, 255)")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.newuser)
        self.label_6.setGeometry(QtCore.QRect(60, 90, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: rgb(255, 255, 255)")
        self.label_6.setObjectName("label_6")
        self.create_single_user_password_line_1 = QtWidgets.QLineEdit(self.newuser)
        self.create_single_user_password_line_1.setGeometry(QtCore.QRect(210, 60, 211, 21))
        self.create_single_user_password_line_1.setStyleSheet("color: rgb(255, 255, 255)")
        self.create_single_user_password_line_1.setText("")
        self.create_single_user_password_line_1.setEchoMode(QtWidgets.QLineEdit.EchoMode.PasswordEchoOnEdit)
        self.create_single_user_password_line_1.setClearButtonEnabled(True)
        self.create_single_user_password_line_1.setObjectName("create_single_user_password_line_1")
        self.create_single_user_password_confirm = QtWidgets.QLineEdit(self.newuser)
        self.create_single_user_password_confirm.setEnabled(True)
        self.create_single_user_password_confirm.setGeometry(QtCore.QRect(210, 90, 211, 21))
        self.create_single_user_password_confirm.setStyleSheet("color: rgb(255, 255, 255)")
        self.create_single_user_password_confirm.setText("")
        self.create_single_user_password_confirm.setEchoMode(QtWidgets.QLineEdit.EchoMode.PasswordEchoOnEdit)
        self.create_single_user_password_confirm.setClearButtonEnabled(True)
        self.create_single_user_password_confirm.setObjectName("create_single_user_password_confirm")
        self.create_new_user_btn = QtWidgets.QPushButton(self.newuser)
        self.create_new_user_btn.setEnabled(True)
        self.create_new_user_btn.setGeometry(QtCore.QRect(220, 160, 111, 24))
        self.create_new_user_btn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.create_new_user_btn.setStyleSheet("QPushButton{\n"
"  border: 1.5px solid white;\n"
"  border-radius: 12px;\n"
"  padding: 5px;\n"
"  color: rgb(255, 255, 255)\n"
"}\n"
"QPushButton:hover{\n"
"  background-color: rgb(199, 199, 199);  \n"
"}\n"
"QPushButton:disabled{\n"
"  color: rgb(199, 199, 199);  \n"
"}")
        self.create_new_user_btn.setObjectName("create_new_user_btn")
        self.label_7 = QtWidgets.QLabel(self.newuser)
        self.label_7.setGeometry(QtCore.QRect(0, 10, 541, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color: rgb(255, 255, 255)")
        self.label_7.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.substackedWidget = QtWidgets.QStackedWidget(self.newuser)
        self.substackedWidget.setGeometry(QtCore.QRect(180, 120, 211, 31))
        self.substackedWidget.setObjectName("substackedWidget")
        self.pass_no_match = QtWidgets.QWidget()
        self.pass_no_match.setObjectName("pass_no_match")
        self.label_2 = QtWidgets.QLabel(self.pass_no_match)
        self.label_2.setGeometry(QtCore.QRect(30, 10, 161, 16))
        self.label_2.setStyleSheet("color: rgb(255, 0, 0)")
        self.label_2.setObjectName("label_2")
        self.substackedWidget.addWidget(self.pass_no_match)
        self.blank_feild = QtWidgets.QWidget()
        self.blank_feild.setObjectName("blank_feild")
        self.label_4 = QtWidgets.QLabel(self.blank_feild)
        self.label_4.setGeometry(QtCore.QRect(30, 10, 161, 16))
        self.label_4.setStyleSheet("color: rgb(255, 0, 0)")
        self.label_4.setObjectName("label_4")
        self.substackedWidget.addWidget(self.blank_feild)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.substackedWidget.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.label_14 = QtWidgets.QLabel(self.page_4)
        self.label_14.setGeometry(QtCore.QRect(30, 10, 101, 16))
        self.label_14.setStyleSheet("color: rgb(255, 0, 0)")
        self.label_14.setObjectName("label_14")
        self.substackedWidget.addWidget(self.page_4)
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.label_15 = QtWidgets.QLabel(self.page_5)
        self.label_15.setGeometry(QtCore.QRect(30, 10, 131, 16))
        self.label_15.setStyleSheet("color: rgb(0, 85, 255)")
        self.label_15.setObjectName("label_15")
        self.substackedWidget.addWidget(self.page_5)
        self.page_6 = QtWidgets.QWidget()
        self.page_6.setObjectName("page_6")
        self.label_16 = QtWidgets.QLabel(self.page_6)
        self.label_16.setGeometry(QtCore.QRect(30, 10, 111, 16))
        self.label_16.setStyleSheet("color: rgb(0, 170, 0)")
        self.label_16.setObjectName("label_16")
        self.substackedWidget.addWidget(self.page_6)
        self.pushButton_2 = QtWidgets.QPushButton(self.newuser)
        self.pushButton_2.setGeometry(QtCore.QRect(430, 60, 91, 24))
        self.pushButton_2.setStyleSheet("QPushButton{\n"
"  border: 1.5px solid white;\n"
"  border-radius: 12px;\n"
"  padding: 5px;\n"
"  color: rgb(255, 255, 255)\n"
"}\n"
"QPushButton:hover{\n"
"  background-color: rgb(199, 199, 199);  \n"
"}\n"
"QPushButton:disabled{\n"
"  color: rgb(199, 199, 199);  \n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.create_new_user_btn_10 = QtWidgets.QPushButton(self.newuser)
        self.create_new_user_btn_10.setEnabled(True)
        self.create_new_user_btn_10.setGeometry(QtCore.QRect(430, 90, 91, 24))
        self.create_new_user_btn_10.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.create_new_user_btn_10.setStyleSheet("QPushButton{\n"
"  border: 1.5px solid white;\n"
"  border-radius: 12px;\n"
"  padding: 5px;\n"
"  color: rgb(255, 255, 255)\n"
"}\n"
"QPushButton:hover{\n"
"  background-color: rgb(199, 199, 199);  \n"
"}\n"
"QPushButton:disabled{\n"
"  color: rgb(199, 199, 199);  \n"
"}")
        self.create_new_user_btn_10.setObjectName("create_new_user_btn_10")
        self.MainstackedWidget.addWidget(self.newuser)
        self.corrupt_vault = QtWidgets.QWidget()
        self.corrupt_vault.setObjectName("corrupt_vault")
        self.label_9 = QtWidgets.QLabel(self.corrupt_vault)
        self.label_9.setGeometry(QtCore.QRect(20, 10, 501, 121))
        self.label_9.setStyleSheet("color: rgb(255, 255, 255)")
        self.label_9.setTextFormat(QtCore.Qt.TextFormat.RichText)
        self.label_9.setObjectName("label_9")
        self.reset = QtWidgets.QPushButton(self.corrupt_vault)
        self.reset.setGeometry(QtCore.QRect(180, 150, 75, 24))
        self.reset.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.reset.setStyleSheet("QPushButton{\n"
"  border: 1.5px solid white;\n"
"  border-radius: 12px;\n"
"  padding: 5px;\n"
"  color: rgb(255, 255, 255)\n"
"}\n"
"QPushButton:hover{\n"
"  background-color: rgb(199, 199, 199);  \n"
"}")
        self.reset.setObjectName("reset")
        self.exit = QtWidgets.QPushButton(self.corrupt_vault)
        self.exit.setGeometry(QtCore.QRect(310, 150, 75, 24))
        self.exit.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.exit.setStyleSheet("QPushButton{\n"
"  border: 1.5px solid white;\n"
"  border-radius: 12px;\n"
"  padding: 5px;\n"
"  color: rgb(255, 255, 255)\n"
"}\n"
"QPushButton:hover{\n"
"  background-color: rgb(199, 199, 199);  \n"
"}")
        self.exit.setObjectName("exit")
        self.MainstackedWidget.addWidget(self.corrupt_vault)
        self.vault_key_missing = QtWidgets.QWidget()
        self.vault_key_missing.setObjectName("vault_key_missing")
        self.exit_vaultkey_modify_2 = QtWidgets.QPushButton(self.vault_key_missing)
        self.exit_vaultkey_modify_2.setGeometry(QtCore.QRect(330, 140, 75, 24))
        self.exit_vaultkey_modify_2.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.exit_vaultkey_modify_2.setStyleSheet("QPushButton{\n"
"  border: 1.5px solid white;\n"
"  border-radius: 12px;\n"
"  padding: 5px;\n"
"  color: rgb(255, 255, 255)\n"
"}\n"
"QPushButton:hover{\n"
"  background-color: rgb(199, 199, 199);  \n"
"}")
        self.exit_vaultkey_modify_2.setObjectName("exit_vaultkey_modify_2")
        self.label_10 = QtWidgets.QLabel(self.vault_key_missing)
        self.label_10.setGeometry(QtCore.QRect(20, 10, 501, 111))
        self.label_10.setStyleSheet("color: rgb(255, 255, 255)")
        self.label_10.setTextFormat(QtCore.Qt.TextFormat.RichText)
        self.label_10.setObjectName("label_10")
        self.reset_vaultkey_modify = QtWidgets.QPushButton(self.vault_key_missing)
        self.reset_vaultkey_modify.setGeometry(QtCore.QRect(230, 140, 75, 24))
        self.reset_vaultkey_modify.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.reset_vaultkey_modify.setStyleSheet("QPushButton{\n"
"  border: 1.5px solid white;\n"
"  border-radius: 12px;\n"
"  padding: 5px;\n"
"  color: rgb(255, 255, 255)\n"
"}\n"
"QPushButton:hover{\n"
"  background-color: rgb(199, 199, 199);  \n"
"}")
        self.reset_vaultkey_modify.setObjectName("reset_vaultkey_modify")
        self.browse = QtWidgets.QPushButton(self.vault_key_missing)
        self.browse.setGeometry(QtCore.QRect(130, 140, 75, 24))
        self.browse.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.browse.setStyleSheet("QPushButton{\n"
"  border: 1.5px solid white;\n"
"  border-radius: 12px;\n"
"  padding: 5px;\n"
"  color: rgb(255, 255, 255)\n"
"}\n"
"QPushButton:hover{\n"
"  background-color: rgb(199, 199, 199);  \n"
"}")
        self.browse.setObjectName("browse")
        self.MainstackedWidget.addWidget(self.vault_key_missing)
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.label_11 = QtWidgets.QLabel(self.page)
        self.label_11.setGeometry(QtCore.QRect(90, 10, 361, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("color: rgb(255, 255, 255)")
        self.label_11.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.confirm_encryption_type = QtWidgets.QPushButton(self.page)
        self.confirm_encryption_type.setGeometry(QtCore.QRect(450, 160, 75, 24))
        self.confirm_encryption_type.setStyleSheet("QPushButton{\n"
"  border: 1.5px solid white;\n"
"  border-radius: 12px;\n"
"  padding: 5px;\n"
"  color: rgb(255, 255, 255)\n"
"}\n"
"QPushButton:hover{\n"
"  background-color: rgb(199, 199, 199);  \n"
"}\n"
"QPushButton:disabled{\n"
"  color: rgb(199, 199, 199);  \n"
"}")
        self.confirm_encryption_type.setObjectName("confirm_encryption_type")
        self.pyaescrypt = QtWidgets.QRadioButton(self.page)
        self.pyaescrypt.setGeometry(QtCore.QRect(30, 50, 89, 20))
        self.pyaescrypt.setStyleSheet("color: rgb(255, 255, 255)")
        self.pyaescrypt.setObjectName("pyaescrypt")
        self.pycryptodome = QtWidgets.QRadioButton(self.page)
        self.pycryptodome.setGeometry(QtCore.QRect(190, 50, 151, 20))
        self.pycryptodome.setStyleSheet("color: rgb(255, 255, 255)")
        self.pycryptodome.setChecked(True)
        self.pycryptodome.setObjectName("pycryptodome")
        self.label_12 = QtWidgets.QLabel(self.page)
        self.label_12.setGeometry(QtCore.QRect(30, 160, 411, 20))
        self.label_12.setStyleSheet("color: rgb(255, 255, 255)")
        self.label_12.setObjectName("label_12")
        self.none = QtWidgets.QRadioButton(self.page)
        self.none.setGeometry(QtCore.QRect(420, 50, 89, 20))
        self.none.setStyleSheet("color: rgb(255, 255, 255)")
        self.none.setObjectName("none")
        self.warning_encrypt = QtWidgets.QStackedWidget(self.page)
        self.warning_encrypt.setGeometry(QtCore.QRect(20, 70, 501, 80))
        self.warning_encrypt.setObjectName("warning_encrypt")
        self.warn_usr = QtWidgets.QWidget()
        self.warn_usr.setObjectName("warn_usr")
        self.label_13 = QtWidgets.QLabel(self.warn_usr)
        self.label_13.setGeometry(QtCore.QRect(10, 10, 481, 51))
        self.label_13.setStyleSheet("color: rgb(255, 0, 0)")
        self.label_13.setWordWrap(True)
        self.label_13.setObjectName("label_13")
        self.warning_encrypt.addWidget(self.warn_usr)
        self.good = QtWidgets.QWidget()
        self.good.setObjectName("good")
        self.warning_encrypt.addWidget(self.good)
        self.MainstackedWidget.addWidget(self.page)
        self.page_7 = QtWidgets.QWidget()
        self.page_7.setObjectName("page_7")
        self.label_17 = QtWidgets.QLabel(self.page_7)
        self.label_17.setGeometry(QtCore.QRect(140, 10, 271, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_17.setFont(font)
        self.label_17.setStyleSheet("color: rgb(255, 255, 255)")
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.page_7)
        self.label_18.setGeometry(QtCore.QRect(30, 160, 411, 20))
        self.label_18.setStyleSheet("color: rgb(255, 255, 255)")
        self.label_18.setObjectName("label_18")
        self.single_user = QtWidgets.QRadioButton(self.page_7)
        self.single_user.setGeometry(QtCore.QRect(140, 70, 89, 20))
        self.single_user.setStyleSheet("color: rgb(255, 255, 255)")
        self.single_user.setChecked(True)
        self.single_user.setObjectName("single_user")
        self.multi_user = QtWidgets.QRadioButton(self.page_7)
        self.multi_user.setGeometry(QtCore.QRect(310, 70, 101, 20))
        self.multi_user.setStyleSheet("color: rgb(255, 255, 255)")
        self.multi_user.setObjectName("multi_user")
        self.okaybutton_2 = QtWidgets.QPushButton(self.page_7)
        self.okaybutton_2.setEnabled(True)
        self.okaybutton_2.setGeometry(QtCore.QRect(450, 160, 75, 24))
        self.okaybutton_2.setStyleSheet("QPushButton{\n"
"  border: 1.5px solid white;\n"
"  border-radius: 12px;\n"
"  padding: 5px;\n"
"  color: rgb(255, 255, 255)\n"
"}\n"
"QPushButton:hover{\n"
"  background-color: rgb(199, 199, 199);  \n"
"}\n"
"QPushButton:disabled{\n"
"  color: rgb(199, 199, 199);  \n"
"}")
        self.okaybutton_2.setObjectName("okaybutton_2")
        self.MainstackedWidget.addWidget(self.page_7)
        self.page_8 = QtWidgets.QWidget()
        self.page_8.setObjectName("page_8")
        self.label_36 = QtWidgets.QLabel(self.page_8)
        self.label_36.setGeometry(QtCore.QRect(40, 110, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_36.setFont(font)
        self.label_36.setStyleSheet("color: rgb(255, 255, 255)")
        self.label_36.setObjectName("label_36")
        self.admin_password = QtWidgets.QLineEdit(self.page_8)
        self.admin_password.setGeometry(QtCore.QRect(190, 80, 211, 21))
        self.admin_password.setStyleSheet("color: rgb(255, 255, 255)")
        self.admin_password.setText("")
        self.admin_password.setEchoMode(QtWidgets.QLineEdit.EchoMode.PasswordEchoOnEdit)
        self.admin_password.setClearButtonEnabled(True)
        self.admin_password.setObjectName("admin_password")
        self.admin_create_account = QtWidgets.QPushButton(self.page_8)
        self.admin_create_account.setEnabled(True)
        self.admin_create_account.setGeometry(QtCore.QRect(410, 110, 111, 24))
        self.admin_create_account.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.admin_create_account.setStyleSheet("QPushButton{\n"
"  border: 1.5px solid white;\n"
"  border-radius: 12px;\n"
"  padding: 5px;\n"
"  color: rgb(255, 255, 255)\n"
"}\n"
"QPushButton:hover{\n"
"  background-color: rgb(199, 199, 199);  \n"
"}\n"
"QPushButton:disabled{\n"
"  color: rgb(199, 199, 199);  \n"
"}")
        self.admin_create_account.setObjectName("admin_create_account")
        self.admin_password_info = QtWidgets.QPushButton(self.page_8)
        self.admin_password_info.setGeometry(QtCore.QRect(410, 50, 111, 24))
        self.admin_password_info.setStyleSheet("QPushButton{\n"
"  border: 1.5px solid white;\n"
"  border-radius: 12px;\n"
"  padding: 5px;\n"
"  color: rgb(255, 255, 255)\n"
"}\n"
"QPushButton:hover{\n"
"  background-color: rgb(199, 199, 199);  \n"
"}\n"
"QPushButton:disabled{\n"
"  color: rgb(199, 199, 199);  \n"
"}")
        self.admin_password_info.setObjectName("admin_password_info")
        self.substackedWidget_3 = QtWidgets.QStackedWidget(self.page_8)
        self.substackedWidget_3.setGeometry(QtCore.QRect(160, 150, 211, 31))
        self.substackedWidget_3.setObjectName("substackedWidget_3")
        self.pass_no_match_3 = QtWidgets.QWidget()
        self.pass_no_match_3.setObjectName("pass_no_match_3")
        self.label_37 = QtWidgets.QLabel(self.pass_no_match_3)
        self.label_37.setGeometry(QtCore.QRect(30, 10, 161, 16))
        self.label_37.setStyleSheet("color: rgb(255, 0, 0)")
        self.label_37.setObjectName("label_37")
        self.substackedWidget_3.addWidget(self.pass_no_match_3)
        self.blank_feild_3 = QtWidgets.QWidget()
        self.blank_feild_3.setObjectName("blank_feild_3")
        self.label_38 = QtWidgets.QLabel(self.blank_feild_3)
        self.label_38.setGeometry(QtCore.QRect(30, 10, 161, 16))
        self.label_38.setStyleSheet("color: rgb(255, 0, 0)")
        self.label_38.setObjectName("label_38")
        self.substackedWidget_3.addWidget(self.blank_feild_3)
        self.page_17 = QtWidgets.QWidget()
        self.page_17.setObjectName("page_17")
        self.substackedWidget_3.addWidget(self.page_17)
        self.page_18 = QtWidgets.QWidget()
        self.page_18.setObjectName("page_18")
        self.label_39 = QtWidgets.QLabel(self.page_18)
        self.label_39.setGeometry(QtCore.QRect(30, 10, 101, 16))
        self.label_39.setStyleSheet("color: rgb(255, 0, 0)")
        self.label_39.setObjectName("label_39")
        self.substackedWidget_3.addWidget(self.page_18)
        self.page_19 = QtWidgets.QWidget()
        self.page_19.setObjectName("page_19")
        self.label_40 = QtWidgets.QLabel(self.page_19)
        self.label_40.setGeometry(QtCore.QRect(30, 10, 131, 16))
        self.label_40.setStyleSheet("color: rgb(0, 85, 255)")
        self.label_40.setObjectName("label_40")
        self.substackedWidget_3.addWidget(self.page_19)
        self.page_20 = QtWidgets.QWidget()
        self.page_20.setObjectName("page_20")
        self.label_41 = QtWidgets.QLabel(self.page_20)
        self.label_41.setGeometry(QtCore.QRect(30, 10, 111, 16))
        self.label_41.setStyleSheet("color: rgb(0, 170, 0)")
        self.label_41.setObjectName("label_41")
        self.substackedWidget_3.addWidget(self.page_20)
        self.admin_confirm_password = QtWidgets.QLineEdit(self.page_8)
        self.admin_confirm_password.setEnabled(True)
        self.admin_confirm_password.setGeometry(QtCore.QRect(190, 110, 211, 21))
        self.admin_confirm_password.setStyleSheet("color: rgb(255, 255, 255)")
        self.admin_confirm_password.setText("")
        self.admin_confirm_password.setEchoMode(QtWidgets.QLineEdit.EchoMode.PasswordEchoOnEdit)
        self.admin_confirm_password.setClearButtonEnabled(True)
        self.admin_confirm_password.setObjectName("admin_confirm_password")
        self.label_42 = QtWidgets.QLabel(self.page_8)
        self.label_42.setGeometry(QtCore.QRect(100, 80, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_42.setFont(font)
        self.label_42.setStyleSheet("color: rgb(255, 255, 255)")
        self.label_42.setObjectName("label_42")
        self.admin_username = QtWidgets.QLineEdit(self.page_8)
        self.admin_username.setGeometry(QtCore.QRect(190, 50, 211, 21))
        self.admin_username.setStyleSheet("color: rgb(255, 255, 255)")
        self.admin_username.setText("")
        self.admin_username.setEchoMode(QtWidgets.QLineEdit.EchoMode.Normal)
        self.admin_username.setClearButtonEnabled(True)
        self.admin_username.setObjectName("admin_username")
        self.label_43 = QtWidgets.QLabel(self.page_8)
        self.label_43.setGeometry(QtCore.QRect(30, 50, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_43.setFont(font)
        self.label_43.setStyleSheet("color: rgb(255, 255, 255)")
        self.label_43.setObjectName("label_43")
        self.label_44 = QtWidgets.QLabel(self.page_8)
        self.label_44.setGeometry(QtCore.QRect(0, 10, 541, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_44.setFont(font)
        self.label_44.setStyleSheet("color: rgb(255, 255, 255)")
        self.label_44.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_44.setObjectName("label_44")
        self.back_to_usr_sel_from_admin = QtWidgets.QPushButton(self.page_8)
        self.back_to_usr_sel_from_admin.setEnabled(True)
        self.back_to_usr_sel_from_admin.setGeometry(QtCore.QRect(410, 80, 111, 24))
        self.back_to_usr_sel_from_admin.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.back_to_usr_sel_from_admin.setStyleSheet("QPushButton{\n"
"  border: 1.5px solid white;\n"
"  border-radius: 12px;\n"
"  padding: 5px;\n"
"  color: rgb(255, 255, 255)\n"
"}\n"
"QPushButton:hover{\n"
"  background-color: rgb(199, 199, 199);  \n"
"}\n"
"QPushButton:disabled{\n"
"  color: rgb(199, 199, 199);  \n"
"}")
        self.back_to_usr_sel_from_admin.setObjectName("back_to_usr_sel_from_admin")
        self.MainstackedWidget.addWidget(self.page_8)
        self.page_21 = QtWidgets.QWidget()
        self.page_21.setObjectName("page_21")
        self.label_45 = QtWidgets.QLabel(self.page_21)
        self.label_45.setGeometry(QtCore.QRect(0, 10, 541, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_45.setFont(font)
        self.label_45.setStyleSheet("color: rgb(255, 255, 255)")
        self.label_45.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_45.setObjectName("label_45")
        self.add_more_users = QtWidgets.QPushButton(self.page_21)
        self.add_more_users.setEnabled(True)
        self.add_more_users.setGeometry(QtCore.QRect(140, 70, 111, 24))
        self.add_more_users.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.add_more_users.setStyleSheet("QPushButton{\n"
"  border: 1.5px solid white;\n"
"  border-radius: 12px;\n"
"  padding: 5px;\n"
"  color: rgb(255, 255, 255)\n"
"}\n"
"QPushButton:hover{\n"
"  background-color: rgb(199, 199, 199);  \n"
"}\n"
"QPushButton:disabled{\n"
"  color: rgb(199, 199, 199);  \n"
"}")
        self.add_more_users.setObjectName("add_more_users")
        self.not_add_more_users = QtWidgets.QPushButton(self.page_21)
        self.not_add_more_users.setEnabled(True)
        self.not_add_more_users.setGeometry(QtCore.QRect(300, 70, 111, 24))
        self.not_add_more_users.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.not_add_more_users.setStyleSheet("QPushButton{\n"
"  border: 1.5px solid white;\n"
"  border-radius: 12px;\n"
"  padding: 5px;\n"
"  color: rgb(255, 255, 255)\n"
"}\n"
"QPushButton:hover{\n"
"  background-color: rgb(199, 199, 199);  \n"
"}\n"
"QPushButton:disabled{\n"
"  color: rgb(199, 199, 199);  \n"
"}")
        self.not_add_more_users.setObjectName("not_add_more_users")
        self.MainstackedWidget.addWidget(self.page_21)
        self.page_22 = QtWidgets.QWidget()
        self.page_22.setObjectName("page_22")
        self.add_usr_new_name = QtWidgets.QLineEdit(self.page_22)
        self.add_usr_new_name.setGeometry(QtCore.QRect(200, 50, 211, 21))
        self.add_usr_new_name.setStyleSheet("color: rgb(255, 255, 255)")
        self.add_usr_new_name.setText("")
        self.add_usr_new_name.setEchoMode(QtWidgets.QLineEdit.EchoMode.PasswordEchoOnEdit)
        self.add_usr_new_name.setClearButtonEnabled(True)
        self.add_usr_new_name.setObjectName("add_usr_new_name")
        self.label_46 = QtWidgets.QLabel(self.page_22)
        self.label_46.setGeometry(QtCore.QRect(40, 10, 101, 16))
        self.label_46.setStyleSheet("color: rgb(255, 0, 0)")
        self.label_46.setObjectName("label_46")
        self.label_47 = QtWidgets.QLabel(self.page_22)
        self.label_47.setGeometry(QtCore.QRect(90, 50, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_47.setFont(font)
        self.label_47.setStyleSheet("color: rgb(255, 255, 255)")
        self.label_47.setObjectName("label_47")
        self.create_more_usr_btn = QtWidgets.QPushButton(self.page_22)
        self.create_more_usr_btn.setEnabled(True)
        self.create_more_usr_btn.setGeometry(QtCore.QRect(420, 160, 111, 24))
        self.create_more_usr_btn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.create_more_usr_btn.setStyleSheet("QPushButton{\n"
"  border: 1.5px solid white;\n"
"  border-radius: 12px;\n"
"  padding: 5px;\n"
"  color: rgb(255, 255, 255)\n"
"}\n"
"QPushButton:hover{\n"
"  background-color: rgb(199, 199, 199);  \n"
"}\n"
"QPushButton:disabled{\n"
"  color: rgb(199, 199, 199);  \n"
"}")
        self.create_more_usr_btn.setObjectName("create_more_usr_btn")
        self.add_usr_confirm_pass = QtWidgets.QLineEdit(self.page_22)
        self.add_usr_confirm_pass.setEnabled(True)
        self.add_usr_confirm_pass.setGeometry(QtCore.QRect(200, 110, 211, 21))
        self.add_usr_confirm_pass.setStyleSheet("color: rgb(255, 255, 255)")
        self.add_usr_confirm_pass.setText("")
        self.add_usr_confirm_pass.setEchoMode(QtWidgets.QLineEdit.EchoMode.PasswordEchoOnEdit)
        self.add_usr_confirm_pass.setClearButtonEnabled(True)
        self.add_usr_confirm_pass.setObjectName("add_usr_confirm_pass")
        self.add_usr_password = QtWidgets.QLineEdit(self.page_22)
        self.add_usr_password.setGeometry(QtCore.QRect(200, 80, 211, 21))
        self.add_usr_password.setStyleSheet("color: rgb(255, 255, 255)")
        self.add_usr_password.setText("")
        self.add_usr_password.setEchoMode(QtWidgets.QLineEdit.EchoMode.PasswordEchoOnEdit)
        self.add_usr_password.setClearButtonEnabled(True)
        self.add_usr_password.setObjectName("add_usr_password")
        self.label_48 = QtWidgets.QLabel(self.page_22)
        self.label_48.setGeometry(QtCore.QRect(10, 10, 541, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_48.setFont(font)
        self.label_48.setStyleSheet("color: rgb(255, 255, 255)")
        self.label_48.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_48.setObjectName("label_48")
        self.label_49 = QtWidgets.QLabel(self.page_22)
        self.label_49.setGeometry(QtCore.QRect(110, 80, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_49.setFont(font)
        self.label_49.setStyleSheet("color: rgb(255, 255, 255)")
        self.label_49.setObjectName("label_49")
        self.add_usr_password_info = QtWidgets.QPushButton(self.page_22)
        self.add_usr_password_info.setGeometry(QtCore.QRect(420, 50, 91, 24))
        self.add_usr_password_info.setStyleSheet("QPushButton{\n"
"  border: 1.5px solid white;\n"
"  border-radius: 12px;\n"
"  padding: 5px;\n"
"  color: rgb(255, 255, 255)\n"
"}\n"
"QPushButton:hover{\n"
"  background-color: rgb(199, 199, 199);  \n"
"}\n"
"QPushButton:disabled{\n"
"  color: rgb(199, 199, 199);  \n"
"}")
        self.add_usr_password_info.setObjectName("add_usr_password_info")
        self.label_50 = QtWidgets.QLabel(self.page_22)
        self.label_50.setGeometry(QtCore.QRect(50, 110, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_50.setFont(font)
        self.label_50.setStyleSheet("color: rgb(255, 255, 255)")
        self.label_50.setObjectName("label_50")
        self.MainstackedWidget.addWidget(self.page_22)
        self.page_25 = QtWidgets.QWidget()
        self.page_25.setObjectName("page_25")
        self.label_52 = QtWidgets.QLabel(self.page_25)
        self.label_52.setGeometry(QtCore.QRect(20, 10, 501, 121))
        self.label_52.setStyleSheet("color: rgb(255, 255, 255)")
        self.label_52.setTextFormat(QtCore.Qt.TextFormat.RichText)
        self.label_52.setObjectName("label_52")
        self.create_new_user_btn_7 = QtWidgets.QPushButton(self.page_25)
        self.create_new_user_btn_7.setEnabled(True)
        self.create_new_user_btn_7.setGeometry(QtCore.QRect(150, 160, 111, 24))
        self.create_new_user_btn_7.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.create_new_user_btn_7.setStyleSheet("QPushButton{\n"
"  border: 1.5px solid white;\n"
"  border-radius: 12px;\n"
"  padding: 5px;\n"
"  color: rgb(255, 255, 255)\n"
"}\n"
"QPushButton:hover{\n"
"  color: rgb(255, 0, 0)\n"
"}\n"
"QPushButton:disabled{\n"
"  color: rgb(199, 199, 199);  \n"
"}")
        self.create_new_user_btn_7.setObjectName("create_new_user_btn_7")
        self.create_new_user_btn_8 = QtWidgets.QPushButton(self.page_25)
        self.create_new_user_btn_8.setEnabled(True)
        self.create_new_user_btn_8.setGeometry(QtCore.QRect(270, 160, 111, 24))
        self.create_new_user_btn_8.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.create_new_user_btn_8.setStyleSheet("QPushButton{\n"
"  border: 1.5px solid white;\n"
"  border-radius: 12px;\n"
"  padding: 5px;\n"
"  color: rgb(255, 255, 255)\n"
"}\n"
"QPushButton:hover{\n"
"  color: rgb(0, 255, 0)\n"
"}\n"
"QPushButton:disabled{\n"
"  color: rgb(199, 199, 199);  \n"
"}")
        self.create_new_user_btn_8.setObjectName("create_new_user_btn_8")
        self.MainstackedWidget.addWidget(self.page_25)
        self.page_26 = QtWidgets.QWidget()
        self.page_26.setObjectName("page_26")
        self.label_53 = QtWidgets.QLabel(self.page_26)
        self.label_53.setGeometry(QtCore.QRect(0, 10, 541, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_53.setFont(font)
        self.label_53.setStyleSheet("color: rgb(255, 255, 255)")
        self.label_53.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_53.setObjectName("label_53")
        self.lineEdit_14 = QtWidgets.QLineEdit(self.page_26)
        self.lineEdit_14.setGeometry(QtCore.QRect(130, 90, 241, 21))
        self.lineEdit_14.setStyleSheet("QLineEdit{\n"
"color: rgb(255, 255, 255)\n"
"}\n"
"QLineEdit:disabled{\n"
"  color: rgb(199, 199, 199);  \n"
"}")
        self.lineEdit_14.setText("")
        self.lineEdit_14.setEchoMode(QtWidgets.QLineEdit.EchoMode.PasswordEchoOnEdit)
        self.lineEdit_14.setClearButtonEnabled(False)
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.unlock_btn_5 = QtWidgets.QPushButton(self.page_26)
        self.unlock_btn_5.setEnabled(True)
        self.unlock_btn_5.setGeometry(QtCore.QRect(200, 160, 161, 31))
        self.unlock_btn_5.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.unlock_btn_5.setStyleSheet("QPushButton{\n"
"  border: none;\n"
"  border-radius: 12px;\n"
"  padding: 5px;\n"
"  color: rgb(255, 255, 255)\n"
"}\n"
"QPushButton:hover{\n"
"  color: rgb(199, 199, 199);  \n"
"}\n"
"QPushButton:disabled{\n"
"  color: rgb(199, 199, 199);  \n"
"}")
        self.unlock_btn_5.setObjectName("unlock_btn_5")
        self.stackedWidgetmp_3 = QtWidgets.QStackedWidget(self.page_26)
        self.stackedWidgetmp_3.setGeometry(QtCore.QRect(400, 40, 131, 71))
        self.stackedWidgetmp_3.setObjectName("stackedWidgetmp_3")
        self.wrongpass_enter_3 = QtWidgets.QWidget()
        self.wrongpass_enter_3.setObjectName("wrongpass_enter_3")
        self.label_54 = QtWidgets.QLabel(self.wrongpass_enter_3)
        self.label_54.setGeometry(QtCore.QRect(10, 30, 91, 20))
        self.label_54.setStyleSheet("color: rgb(255, 0, 0)\n"
"")
        self.label_54.setObjectName("label_54")
        self.stackedWidgetmp_3.addWidget(self.wrongpass_enter_3)
        self.page_27 = QtWidgets.QWidget()
        self.page_27.setObjectName("page_27")
        self.stackedWidgetmp_3.addWidget(self.page_27)
        self.unlock_btn_6 = QtWidgets.QPushButton(self.page_26)
        self.unlock_btn_6.setEnabled(True)
        self.unlock_btn_6.setGeometry(QtCore.QRect(240, 130, 75, 24))
        self.unlock_btn_6.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.unlock_btn_6.setStyleSheet("QPushButton{\n"
"  border: 1.5px solid white;\n"
"  border-radius: 12px;\n"
"  padding: 5px;\n"
"  color: rgb(255, 255, 255)\n"
"}\n"
"QPushButton:hover{\n"
"  background-color: rgb(199, 199, 199);  \n"
"}\n"
"QPushButton:disabled{\n"
"  color: rgb(199, 199, 199);  \n"
"}")
        self.unlock_btn_6.setObjectName("unlock_btn_6")
        self.label_55 = QtWidgets.QLabel(self.page_26)
        self.label_55.setGeometry(QtCore.QRect(20, 50, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_55.setFont(font)
        self.label_55.setStyleSheet("color: rgb(255, 255, 255)")
        self.label_55.setObjectName("label_55")
        self.label_56 = QtWidgets.QLabel(self.page_26)
        self.label_56.setGeometry(QtCore.QRect(30, 90, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_56.setFont(font)
        self.label_56.setStyleSheet("color: rgb(255, 255, 255)")
        self.label_56.setObjectName("label_56")
        self.comboBox = QtWidgets.QComboBox(self.page_26)
        self.comboBox.setGeometry(QtCore.QRect(130, 50, 241, 22))
        self.comboBox.setStyleSheet("#comboBox{\n"
" border: 1px solid white #ced4da;\n"
" border-radius: 4 px;\n"
" padding-left: 4px\n"
"}\n"
"\n"
"#comboBox::down-down{\n"
" border: 0px\n"
"}\n"
"\n"
"#comboBox::down-arrow{\n"
" image: url(:/icon/chevron-down.svg)\n"
"}\n"
"")
        self.comboBox.setObjectName("comboBox")
        self.MainstackedWidget.addWidget(self.page_26)
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setGeometry(QtCore.QRect(-71, 0, 621, 241))
        self.frame.setStyleSheet("QFrame{\n"
"  \n"
"    background-color: rgb(56, 58, 89);\n"
"    color: rgb(220, 220, 220);\n"
"    border-radius:10px\n"
"}\n"
"\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame)
        self.stackedWidget.setGeometry(QtCore.QRect(240, 0, 201, 41))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_23 = QtWidgets.QWidget()
        self.page_23.setObjectName("page_23")
        self.label = QtWidgets.QLabel(self.page_23)
        self.label.setGeometry(QtCore.QRect(-10, -10, 221, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 255, 255)")
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.stackedWidget.addWidget(self.page_23)
        self.page_24 = QtWidgets.QWidget()
        self.page_24.setObjectName("page_24")
        self.label_51 = QtWidgets.QLabel(self.page_24)
        self.label_51.setGeometry(QtCore.QRect(-10, -10, 231, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_51.setFont(font)
        self.label_51.setStyleSheet("color: rgb(255, 255, 255)")
        self.label_51.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_51.setObjectName("label_51")
        self.stackedWidget.addWidget(self.page_24)
        self.frame.raise_()
        self.MainstackedWidget.raise_()

        self.retranslateUi(Dialog)
        self.MainstackedWidget.setCurrentIndex(8)
        self.stackedWidgetmp.setCurrentIndex(1)
        self.substackedWidget.setCurrentIndex(2)
        self.warning_encrypt.setCurrentIndex(1)
        self.substackedWidget_3.setCurrentIndex(2)
        self.stackedWidgetmp_3.setCurrentIndex(1)
        self.stackedWidget.setCurrentIndex(1)
        self.exit.clicked.connect(Dialog.close) # type: ignore
        self.exit_vaultkey_modify_2.clicked.connect(Dialog.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.unlock_btn.setText(_translate("Dialog", "Unlock"))
        self.label_3.setText(_translate("Dialog", "Enter Master Password To Continue"))
        self.forgot_password.setText(_translate("Dialog", "Forgot Your Main Password?"))
        self.label_8.setText(_translate("Dialog", "Wrong Password!"))
        self.label_5.setText(_translate("Dialog", "Password:"))
        self.label_6.setText(_translate("Dialog", "Confirm Password:"))
        self.create_new_user_btn.setText(_translate("Dialog", "Create New Vault"))
        self.label_7.setText(_translate("Dialog", "To Create A New Vault Enter The Master Password"))
        self.label_2.setText(_translate("Dialog", "Your Passwords Don\'t Match"))
        self.label_4.setText(_translate("Dialog", "Please Enter Your Password"))
        self.label_14.setText(_translate("Dialog", "Password Is Weak"))
        self.label_15.setText(_translate("Dialog", "Password Is Moderate"))
        self.label_16.setText(_translate("Dialog", "Password Is Strong"))
        self.pushButton_2.setText(_translate("Dialog", "Password Info"))
        self.create_new_user_btn_10.setText(_translate("Dialog", "Back"))
        self.label_9.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt;\">Looks Like Your Vault Is Corrupted Or Has Been Modified. </span></p><p align=\"center\"><span style=\" font-size:14pt;\">To Continue Please Reset Your Vault.</span></p><p align=\"center\"><span style=\" font-size:14pt; color:#ff0000;\">Note: Resetting Will Delete Your Old Data.</span></p></body></html>"))
        self.reset.setText(_translate("Dialog", "Reset"))
        self.exit.setText(_translate("Dialog", "Exit"))
        self.exit_vaultkey_modify_2.setText(_translate("Dialog", "Exit"))
        self.label_10.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt;\">Looks Like Your Vault Security Key Is Modified. </span></p><p align=\"center\"><span style=\" font-size:14pt;\">To Continue Please Browse The Key Or Reset Your Vault.</span></p><p align=\"center\"><span style=\" font-size:14pt; color:#ff0000;\">Note: Resetting Will Delete Your Old Data.</span></p></body></html>"))
        self.reset_vaultkey_modify.setText(_translate("Dialog", "Reset"))
        self.browse.setText(_translate("Dialog", "Browse"))
        self.label_11.setText(_translate("Dialog", "Please Select You Preferred Method For Encryption"))
        self.confirm_encryption_type.setText(_translate("Dialog", "Ok"))
        self.pyaescrypt.setText(_translate("Dialog", "PyAesCrypt"))
        self.pycryptodome.setText(_translate("Dialog", "PyCryptoDome [Default]"))
        self.label_12.setText(_translate("Dialog", "Note: This Cannot Be Changed Later. To Change You Have To Reset The Vault"))
        self.none.setText(_translate("Dialog", "None"))
        self.label_13.setText(_translate("Dialog", "Anyone Can Access Your Data Without Your Consent. The Vault Will Just Be Hidden Under Your Master Password."))
        self.label_17.setText(_translate("Dialog", "Please Select The Preffered User Mode"))
        self.label_18.setText(_translate("Dialog", "Note: This Cannot Be Changed Later. To Change You Have To Reset The Vault"))
        self.single_user.setText(_translate("Dialog", "Single User"))
        self.multi_user.setText(_translate("Dialog", "Multiple Users"))
        self.okaybutton_2.setText(_translate("Dialog", "Ok"))
        self.label_36.setText(_translate("Dialog", "Confirm Password:"))
        self.admin_create_account.setText(_translate("Dialog", "Create New Vault"))
        self.admin_password_info.setText(_translate("Dialog", "Password Info"))
        self.label_37.setText(_translate("Dialog", "Your Passwords Don\'t Match"))
        self.label_38.setText(_translate("Dialog", "Please Enter Your Password"))
        self.label_39.setText(_translate("Dialog", "Password Is Weak"))
        self.label_40.setText(_translate("Dialog", "Password Is Moderate"))
        self.label_41.setText(_translate("Dialog", "Password Is Strong"))
        self.label_42.setText(_translate("Dialog", "Password:"))
        self.label_43.setText(_translate("Dialog", "  Admin User Name:"))
        self.label_44.setText(_translate("Dialog", "Please Fill Out The Following Details"))
        self.back_to_usr_sel_from_admin.setText(_translate("Dialog", "Back"))
        self.label_45.setText(_translate("Dialog", "Want To Add Users?"))
        self.add_more_users.setText(_translate("Dialog", "Yes!"))
        self.not_add_more_users.setText(_translate("Dialog", "No Thanks!"))
        self.label_46.setText(_translate("Dialog", "Password Is Weak"))
        self.label_47.setText(_translate("Dialog", " User Name:"))
        self.create_more_usr_btn.setText(_translate("Dialog", "Create New Vault"))
        self.label_48.setText(_translate("Dialog", "Please Fill Out The Following Details"))
        self.label_49.setText(_translate("Dialog", "Password:"))
        self.add_usr_password_info.setText(_translate("Dialog", "Password Info"))
        self.label_50.setText(_translate("Dialog", "Confirm Password:"))
        self.label_52.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt;\">Do You Want To Reset Your Vault?</span></p><p><br/></p><p align=\"center\"><span style=\" font-size:14pt; color:#ff0000;\">Note: Resetting Will Delete Your Old Data.</span></p></body></html>"))
        self.create_new_user_btn_7.setText(_translate("Dialog", "Yes"))
        self.create_new_user_btn_8.setText(_translate("Dialog", "No"))
        self.label_53.setText(_translate("Dialog", "Enter Your Required Details"))
        self.unlock_btn_5.setText(_translate("Dialog", "Create New Account"))
        self.label_54.setText(_translate("Dialog", "Wrong Password!"))
        self.unlock_btn_6.setText(_translate("Dialog", "Unlock"))
        self.label_55.setText(_translate("Dialog", " User Name:"))
        self.label_56.setText(_translate("Dialog", " Password:"))
        self.label.setText(_translate("Dialog", "Good Morning!"))
        self.label_51.setText(_translate("Dialog", "Good Evening!"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
