from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 505)
        Dialog.setMinimumSize(QtCore.QSize(400, 505))
        Dialog.setMaximumSize(QtCore.QSize(400, 505))
        Dialog.setAcceptDrops(False)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(10, 10, 381, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.spinBox = QtWidgets.QSpinBox(Dialog)
        self.spinBox.setGeometry(QtCore.QRect(180, 250, 51, 22))
        self.spinBox.setStyleSheet("")
        self.spinBox.setMinimum(5)
        self.spinBox.setMaximum(135)
        self.spinBox.setProperty("value", 20)
        self.spinBox.setDisplayIntegerBase(10)
        self.spinBox.setObjectName("spinBox")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(40, 250, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.line = QtWidgets.QFrame(Dialog)
        self.line.setGeometry(QtCore.QRect(0, 50, 401, 20))
        self.line.setStyleSheet("line{\n"
"    border-color: rgb(184, 184, 184);\n"
"}")
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.line.setLineWidth(1)
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(Dialog)
        self.line_2.setGeometry(QtCore.QRect(0, 210, 401, 20))
        self.line_2.setStyleSheet("line{\n"
"    border-color: rgb(184, 184, 184);\n"
"}")
        self.line_2.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.line_2.setLineWidth(1)
        self.line_2.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(Dialog)
        self.line_3.setGeometry(QtCore.QRect(40, 290, 321, 20))
        self.line_3.setStyleSheet("line{\n"
"    border-color: rgb(184, 184, 184);\n"
"}")
        self.line_3.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.line_3.setLineWidth(1)
        self.line_3.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_3.setObjectName("line_3")
        self.checkBox = QtWidgets.QCheckBox(Dialog)
        self.checkBox.setGeometry(QtCore.QRect(40, 350, 161, 20))
        self.checkBox.setChecked(True)
        self.checkBox.setObjectName("checkBox")
        self.checkBox_2 = QtWidgets.QCheckBox(Dialog)
        self.checkBox_2.setGeometry(QtCore.QRect(40, 380, 161, 20))
        self.checkBox_2.setChecked(True)
        self.checkBox_2.setObjectName("checkBox_2")
        self.checkBox_3 = QtWidgets.QCheckBox(Dialog)
        self.checkBox_3.setGeometry(QtCore.QRect(40, 410, 161, 20))
        self.checkBox_3.setChecked(True)
        self.checkBox_3.setObjectName("checkBox_3")
        self.checkBox_4 = QtWidgets.QCheckBox(Dialog)
        self.checkBox_4.setGeometry(QtCore.QRect(40, 440, 16, 20))
        self.checkBox_4.setText("")
        self.checkBox_4.setChecked(True)
        self.checkBox_4.setObjectName("checkBox_4")
        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        self.lineEdit.setEnabled(True)
        self.lineEdit.setGeometry(QtCore.QRect(60, 440, 211, 21))
        self.lineEdit.setObjectName("lineEdit")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(40, 310, 321, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.stackedWidget = QtWidgets.QStackedWidget(Dialog)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 70, 401, 141))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.pushButton = QtWidgets.QPushButton(self.page_3)
        self.pushButton.setGeometry(QtCore.QRect(90, 110, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.pushButton.setFont(font)
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushButton.setStyleSheet("QPushButton{\n"
"  border: 1.5px solid black;\n"
"  border-radius: 15px;\n"
"  padding: 5px;\n"
"}\n"
"QPushButton:hover{\n"
"  background-color: rgb(213, 213, 213);  \n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/copy.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setIconSize(QtCore.QSize(0, 0))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.page_3)
        self.pushButton_2.setGeometry(QtCore.QRect(350, 20, 41, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.pushButton_2.setFont(font)
        self.pushButton_2.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushButton_2.setWhatsThis("")
        self.pushButton_2.setAccessibleName("")
        self.pushButton_2.setAccessibleDescription("")
        self.pushButton_2.setStyleSheet("QPushButton{\n"
"  border: 1.5px solid black;\n"
"  border-radius: 15px;\n"
"  padding: 5px;\n"
"}\n"
"QPushButton:hover{\n"
"  background-color: rgb(213, 213, 213);  \n"
"}")
        self.pushButton_2.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/refresh-ccw.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_2.setIcon(icon1)
        self.pushButton_2.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_2.setFlat(True)
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_5 = QtWidgets.QLabel(self.page_3)
        self.label_5.setGeometry(QtCore.QRect(60, 20, 281, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_5.setFont(font)
        self.label_5.setText("")
        self.label_5.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.weakpass = QtWidgets.QStackedWidget(self.page_3)
        self.weakpass.setGeometry(QtCore.QRect(20, 70, 291, 31))
        self.weakpass.setObjectName("weakpass")
        self.weak = QtWidgets.QWidget()
        self.weak.setObjectName("weak")
        self.label_6 = QtWidgets.QLabel(self.weak)
        self.label_6.setGeometry(QtCore.QRect(80, 10, 191, 16))
        self.label_6.setStyleSheet("color: rgb(255, 0, 0)")
        self.label_6.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.weakpass.addWidget(self.weak)
        self.moderate = QtWidgets.QWidget()
        self.moderate.setObjectName("moderate")
        self.label_7 = QtWidgets.QLabel(self.moderate)
        self.label_7.setGeometry(QtCore.QRect(80, 10, 201, 16))
        self.label_7.setStyleSheet("color: rgb(0, 85, 255)")
        self.label_7.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.weakpass.addWidget(self.moderate)
        self.strong = QtWidgets.QWidget()
        self.strong.setObjectName("strong")
        self.label_8 = QtWidgets.QLabel(self.strong)
        self.label_8.setGeometry(QtCore.QRect(80, 10, 191, 16))
        self.label_8.setStyleSheet("color: rgb(0, 170, 0)")
        self.label_8.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.weakpass.addWidget(self.strong)
        self.none = QtWidgets.QWidget()
        self.none.setObjectName("none")
        self.weakpass.addWidget(self.none)
        self.pushButton_3 = QtWidgets.QPushButton(self.page_3)
        self.pushButton_3.setGeometry(QtCore.QRect(210, 110, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushButton_3.setStyleSheet("QPushButton{\n"
"  border: 1.5px solid black;\n"
"  border-radius: 15px;\n"
"  padding: 5px;\n"
"}\n"
"QPushButton:hover{\n"
"  background-color: rgb(213, 213, 213);  \n"
"}")
        self.pushButton_3.setIcon(icon)
        self.pushButton_3.setIconSize(QtCore.QSize(0, 0))
        self.pushButton_3.setObjectName("pushButton_3")
        self.stackedWidget.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.label_4 = QtWidgets.QLabel(self.page_4)
        self.label_4.setGeometry(QtCore.QRect(0, 50, 401, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(255, 0, 0)")
        self.label_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.stackedWidget.addWidget(self.page_4)
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.label_9 = QtWidgets.QLabel(self.page)
        self.label_9.setGeometry(QtCore.QRect(100, 60, 191, 31))
        self.label_9.setText("")
        self.label_9.setObjectName("label_9")
        self.stackedWidget.addWidget(self.page)

        self.retranslateUi(Dialog)
        self.stackedWidget.setCurrentIndex(0)
        self.weakpass.setCurrentIndex(3)
        self.checkBox_4.toggled['bool'].connect(self.lineEdit.setEnabled) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Password Generator"))
        self.label_2.setText(_translate("Dialog", "Password Lenght:"))
        self.checkBox.setText(_translate("Dialog", "Uppercase Letters (A-Z)"))
        self.checkBox_2.setText(_translate("Dialog", "Lowercase Letters (a-z)"))
        self.checkBox_3.setText(_translate("Dialog", "Digits (0-9)"))
        self.lineEdit.setText(_translate("Dialog", "~!@#$%^&*+-/.,\\{}[]();:|?<>=\"\'`"))
        self.label_3.setText(_translate("Dialog", "Customize Your Choices"))
        self.pushButton.setText(_translate("Dialog", "Copy"))
        self.label_6.setText(_translate("Dialog", "Your Password Strenght Is Weak"))
        self.label_7.setText(_translate("Dialog", "Your Password Strenght Is Moderate"))
        self.label_8.setText(_translate("Dialog", "Your Password Strenght Is Strong"))
        self.pushButton_3.setText(_translate("Dialog", "Password Info"))
        self.label_4.setText(_translate("Dialog", "Please Select Atleast One Checkbox To Generate A New Passoword."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
