from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(980, 580)
        MainWindow.setMinimumSize(QtCore.QSize(978, 580))
        MainWindow.setMaximumSize(QtCore.QSize(980, 578))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Main = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Main.sizePolicy().hasHeightForWidth())
        self.Main.setSizePolicy(sizePolicy)
        self.Main.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.Main.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.Main.setObjectName("Main")
        self.frame = QtWidgets.QFrame(self.Main)
        self.frame.setGeometry(QtCore.QRect(0, 0, 111, 541))
        self.frame.setStyleSheet("")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setGeometry(QtCore.QRect(1, 170, 111, 171))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.create_entry = QtWidgets.QPushButton(self.frame_2)
        self.create_entry.setGeometry(QtCore.QRect(10, 120, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.create_entry.setFont(font)
        self.create_entry.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        self.create_entry.setToolTip("Create New Entry")
        self.create_entry.setStyleSheet("QPushButton{\n"
"  border: 1.5px solid black;\n"
"  border-radius: 15px;\n"
"  padding: 5px;\n"
"}\n"
"QPushButton:hover{\n"
"  background-color: rgb(213, 213, 213);  \n"
"}")
        self.create_entry.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../Data Manager/Project MEW/GUI INTERFACE/icons/plus-circle.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.create_entry.setIcon(icon)
        self.create_entry.setIconSize(QtCore.QSize(24, 24))
        self.create_entry.setObjectName("create_entry")
        self.passwordgen = QtWidgets.QPushButton(self.frame_2)
        self.passwordgen.setGeometry(QtCore.QRect(20, 40, 61, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.passwordgen.sizePolicy().hasHeightForWidth())
        self.passwordgen.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.passwordgen.setFont(font)
        self.passwordgen.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        self.passwordgen.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.NoContextMenu)
        self.passwordgen.setAcceptDrops(False)
        self.passwordgen.setToolTip("Generate Passwords")
        self.passwordgen.setToolTipDuration(-1)
        self.passwordgen.setStyleSheet("QPushButton{\n"
"  border: 1.5px solid black;\n"
"  border-radius: 15px;\n"
"  padding: 5px;\n"
"}\n"
"QPushButton:hover{\n"
"  background-color: rgb(213, 213, 213);  \n"
"}")
        self.passwordgen.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/newPrefix/icons/key.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.passwordgen.setIcon(icon1)
        self.passwordgen.setIconSize(QtCore.QSize(24, 24))
        self.passwordgen.setObjectName("passwordgen")
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setGeometry(QtCore.QRect(20, 10, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.create_folder = QtWidgets.QPushButton(self.frame_2)
        self.create_folder.setGeometry(QtCore.QRect(60, 120, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.create_folder.setFont(font)
        self.create_folder.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        self.create_folder.setToolTip("Create New Folder")
        self.create_folder.setStyleSheet("QPushButton{\n"
"  border: 1.5px solid black;\n"
"  border-radius: 15px;\n"
"  padding: 5px;\n"
"}\n"
"QPushButton:hover{\n"
"  background-color: rgb(213, 213, 213);  \n"
"}")
        self.create_folder.setText("")
        self.create_folder.setIcon(icon)
        self.create_folder.setIconSize(QtCore.QSize(24, 24))
        self.create_folder.setObjectName("create_folder")
        self.label_13 = QtWidgets.QLabel(self.frame_2)
        self.label_13.setGeometry(QtCore.QRect(30, 90, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setGeometry(QtCore.QRect(1, 320, 111, 181))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setStyleSheet("")
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.settings = QtWidgets.QPushButton(self.frame_3)
        self.settings.setGeometry(QtCore.QRect(20, 70, 61, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.settings.setFont(font)
        self.settings.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        self.settings.setToolTip("Open Settings")
        self.settings.setStyleSheet("QPushButton{\n"
"  border: 1.5px solid black;\n"
"  border-radius: 15px;\n"
"  padding: 5px;\n"
"}\n"
"QPushButton:hover{\n"
"  background-color: rgb(213, 213, 213);  \n"
"}")
        self.settings.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/newPrefix/icons/settings.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.settings.setIcon(icon2)
        self.settings.setIconSize(QtCore.QSize(24, 24))
        self.settings.setObjectName("settings")
        self.about = QtWidgets.QPushButton(self.frame_3)
        self.about.setGeometry(QtCore.QRect(20, 130, 61, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.about.setFont(font)
        self.about.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        self.about.setToolTip("About")
        self.about.setStyleSheet("QPushButton{\n"
"  border: 1.5px solid black;\n"
"  border-radius: 15px;\n"
"  padding: 5px;\n"
"}\n"
"QPushButton:hover{\n"
"  background-color: rgb(213, 213, 213);  \n"
"}")
        self.about.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/newPrefix/icons/info.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.about.setIcon(icon3)
        self.about.setIconSize(QtCore.QSize(24, 24))
        self.about.setObjectName("about")
        self.label_3 = QtWidgets.QLabel(self.frame_3)
        self.label_3.setGeometry(QtCore.QRect(30, 20, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.allentry = QtWidgets.QFrame(self.frame)
        self.allentry.setGeometry(QtCore.QRect(1, 10, 101, 171))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.allentry.sizePolicy().hasHeightForWidth())
        self.allentry.setSizePolicy(sizePolicy)
        self.allentry.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.allentry.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.allentry.setObjectName("allentry")
        self.vault_2 = QtWidgets.QPushButton(self.allentry)
        self.vault_2.setGeometry(QtCore.QRect(20, 100, 61, 41))
        self.vault_2.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.vault_2.setFont(font)
        self.vault_2.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        self.vault_2.setToolTip("Shows All Stored Data")
        self.vault_2.setStyleSheet("QPushButton{\n"
"  border: 1.5px solid black;\n"
"  border-radius: 15px;\n"
"  padding: 5px;\n"
"}\n"
"QPushButton:hover{\n"
"  background-color: rgb(213, 213, 213);  \n"
"}")
        self.vault_2.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/newPrefix/icons/database.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.vault_2.setIcon(icon4)
        self.vault_2.setIconSize(QtCore.QSize(24, 24))
        self.vault_2.setObjectName("vault_2")
        self.label = QtWidgets.QLabel(self.allentry)
        self.label.setGeometry(QtCore.QRect(20, 16, 71, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.main = QtWidgets.QPushButton(self.allentry)
        self.main.setGeometry(QtCore.QRect(20, 50, 61, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.main.setFont(font)
        self.main.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        self.main.setToolTip("Open Main")
        self.main.setToolTipDuration(-1)
        self.main.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.main.setStyleSheet("QPushButton{\n"
"  border: 1.5px solid black;\n"
"  border-radius: 15px;\n"
"  padding: 5px;\n"
"}\n"
"QPushButton:hover{\n"
"  background-color: rgb(213, 213, 213);  \n"
"}")
        self.main.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/newPrefix/icons/home.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.main.setIcon(icon5)
        self.main.setIconSize(QtCore.QSize(24, 24))
        self.main.setObjectName("main")
        self.line = QtWidgets.QFrame(self.frame)
        self.line.setGeometry(QtCore.QRect(0, -1, 110, 20))
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.frame)
        self.line_2.setGeometry(QtCore.QRect(0, 510, 108, 20))
        self.line_2.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.line_2.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.frame)
        self.line_3.setGeometry(QtCore.QRect(99, 9, 20, 512))
        self.line_3.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.line_3.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtWidgets.QFrame(self.frame)
        self.line_4.setGeometry(QtCore.QRect(-9, 9, 20, 510))
        self.line_4.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.line_4.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_4.setObjectName("line_4")
        self.component = QtWidgets.QFrame(self.Main)
        self.component.setGeometry(QtCore.QRect(110, 0, 851, 541))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.component.sizePolicy().hasHeightForWidth())
        self.component.setSizePolicy(sizePolicy)
        self.component.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.component.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.component.setObjectName("component")
        self.frame_4 = QtWidgets.QFrame(self.component)
        self.frame_4.setGeometry(QtCore.QRect(0, 50, 261, 531))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_4.sizePolicy().hasHeightForWidth())
        self.frame_4.setSizePolicy(sizePolicy)
        self.frame_4.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_4.setObjectName("frame_4")
        self.tabWidget = QtWidgets.QTabWidget(self.frame_4)
        self.tabWidget.setGeometry(QtCore.QRect(10, 0, 261, 441))
        self.tabWidget.setObjectName("tabWidget")
        self.Entries = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Entries.sizePolicy().hasHeightForWidth())
        self.Entries.setSizePolicy(sizePolicy)
        self.Entries.setObjectName("Entries")
        self.scrollArea_3 = QtWidgets.QScrollArea(self.Entries)
        self.scrollArea_3.setGeometry(QtCore.QRect(-3, 0, 251, 412))
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollArea_3.setObjectName("scrollArea_3")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 249, 410))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollAreaWidgetContents_3.sizePolicy().hasHeightForWidth())
        self.scrollAreaWidgetContents_3.setSizePolicy(sizePolicy)
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_3)
        self.tabWidget.addTab(self.Entries, "")
        self.FolderSelection = QtWidgets.QWidget()
        self.FolderSelection.setObjectName("FolderSelection")
        self.scrollArea_2 = QtWidgets.QScrollArea(self.FolderSelection)
        self.scrollArea_2.setGeometry(QtCore.QRect(-3, 0, 251, 411))
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 249, 409))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollAreaWidgetContents_2.sizePolicy().hasHeightForWidth())
        self.scrollAreaWidgetContents_2.setSizePolicy(sizePolicy)
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.tabWidget.addTab(self.FolderSelection, "")
        self.item_widget = QtWidgets.QFrame(self.component)
        self.item_widget.setGeometry(QtCore.QRect(260, 70, 591, 421))
        self.item_widget.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.item_widget.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.item_widget.setObjectName("item_widget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.item_widget)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 0, 591, 451))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.label_8 = QtWidgets.QLabel(self.page)
        self.label_8.setGeometry(QtCore.QRect(120, 160, 341, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.create_folder_2 = QtWidgets.QPushButton(self.page)
        self.create_folder_2.setGeometry(QtCore.QRect(250, 220, 81, 71))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.create_folder_2.setFont(font)
        self.create_folder_2.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        self.create_folder_2.setToolTip("Create New Folder")
        self.create_folder_2.setStyleSheet("QPushButton{\n"
"  border: 1.5px solid black;\n"
"  border-radius: 15px;\n"
"  padding: 5px;\n"
"}\n"
"QPushButton:hover{\n"
"  background-color: rgb(213, 213, 213);  \n"
"}")
        self.create_folder_2.setText("")
        self.create_folder_2.setIcon(icon)
        self.create_folder_2.setIconSize(QtCore.QSize(24, 24))
        self.create_folder_2.setObjectName("create_folder_2")
        self.passwordgen_2 = QtWidgets.QPushButton(self.page)
        self.passwordgen_2.setGeometry(QtCore.QRect(370, 220, 81, 71))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.passwordgen_2.sizePolicy().hasHeightForWidth())
        self.passwordgen_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.passwordgen_2.setFont(font)
        self.passwordgen_2.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        self.passwordgen_2.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.NoContextMenu)
        self.passwordgen_2.setAcceptDrops(False)
        self.passwordgen_2.setToolTip("Generate Passwords")
        self.passwordgen_2.setToolTipDuration(-1)
        self.passwordgen_2.setStyleSheet("QPushButton{\n"
"  border: 1.5px solid black;\n"
"  border-radius: 15px;\n"
"  padding: 5px;\n"
"}\n"
"QPushButton:hover{\n"
"  background-color: rgb(213, 213, 213);  \n"
"}")
        self.passwordgen_2.setText("")
        self.passwordgen_2.setIcon(icon1)
        self.passwordgen_2.setIconSize(QtCore.QSize(24, 24))
        self.passwordgen_2.setObjectName("passwordgen_2")
        self.create_entry_2 = QtWidgets.QPushButton(self.page)
        self.create_entry_2.setGeometry(QtCore.QRect(130, 220, 81, 71))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.create_entry_2.setFont(font)
        self.create_entry_2.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        self.create_entry_2.setToolTip("Create New Entry")
        self.create_entry_2.setStyleSheet("QPushButton{\n"
"  border: 1.5px solid black;\n"
"  border-radius: 15px;\n"
"  padding: 5px;\n"
"}\n"
"QPushButton:hover{\n"
"  background-color: rgb(213, 213, 213);  \n"
"}")
        self.create_entry_2.setText("")
        self.create_entry_2.setIcon(icon)
        self.create_entry_2.setIconSize(QtCore.QSize(24, 24))
        self.create_entry_2.setObjectName("create_entry_2")
        self.label_16 = QtWidgets.QLabel(self.page)
        self.label_16.setGeometry(QtCore.QRect(125, 310, 91, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_16.setFont(font)
        self.label_16.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.page)
        self.label_17.setGeometry(QtCore.QRect(250, 310, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_17.setFont(font)
        self.label_17.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.page)
        self.label_18.setGeometry(QtCore.QRect(350, 310, 131, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_18.setFont(font)
        self.label_18.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.scrollArea = QtWidgets.QScrollArea(self.page_2)
        self.scrollArea.setGeometry(QtCore.QRect(0, 5, 581, 411))
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAsNeeded)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 579, 409))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.label_9 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_9.setGeometry(QtCore.QRect(9, 36, 91, 16))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_10.setGeometry(QtCore.QRect(9, 111, 62, 16))
        self.label_10.setObjectName("label_10")
        self.web_address = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.web_address.setGeometry(QtCore.QRect(9, 58, 471, 21))
        self.web_address.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhUrlCharactersOnly)
        self.web_address.setObjectName("web_address")
        self.primary_websitedomain = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.primary_websitedomain.setGeometry(QtCore.QRect(9, 85, 243, 20))
        self.primary_websitedomain.setChecked(True)
        self.primary_websitedomain.setObjectName("primary_websitedomain")
        self.user_name = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.user_name.setGeometry(QtCore.QRect(9, 133, 471, 21))
        self.user_name.setObjectName("user_name")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_2.setGeometry(QtCore.QRect(160, 9, 281, 21))
        self.lineEdit_2.setAccessibleName("")
        self.lineEdit_2.setInputMask("")
        self.lineEdit_2.setText("")
        self.lineEdit_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_11 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_11.setGeometry(QtCore.QRect(9, 160, 53, 16))
        self.label_11.setObjectName("label_11")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_3.setGeometry(QtCore.QRect(9, 182, 441, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_3.sizePolicy().hasHeightForWidth())
        self.lineEdit_3.setSizePolicy(sizePolicy)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.notes = QtWidgets.QTextEdit(self.scrollAreaWidgetContents)
        self.notes.setGeometry(QtCore.QRect(9, 231, 544, 121))
        self.notes.setObjectName("notes")
        self.label_12 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_12.setGeometry(QtCore.QRect(9, 209, 34, 16))
        self.label_12.setObjectName("label_12")
        self.stackedWidget_2 = QtWidgets.QStackedWidget(self.scrollAreaWidgetContents)
        self.stackedWidget_2.setGeometry(QtCore.QRect(460, 170, 31, 41))
        self.stackedWidget_2.setObjectName("stackedWidget_2")
        self.page_8 = QtWidgets.QWidget()
        self.page_8.setObjectName("page_8")
        self.pushButton = QtWidgets.QPushButton(self.page_8)
        self.pushButton.setGeometry(QtCore.QRect(0, 10, 31, 24))
        self.pushButton.setStyleSheet("QPushButton{\n"
"  border: 1.5px solid black;\n"
"  border-radius: 12px;\n"
"  padding: 5px;\n"
"}\n"
"QPushButton:hover{\n"
"  background-color: rgb(213, 213, 213);  \n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.stackedWidget_2.addWidget(self.page_8)
        self.page_9 = QtWidgets.QWidget()
        self.page_9.setObjectName("page_9")
        self.stackedWidget_2.addWidget(self.page_9)
        self.stackedWidget_3 = QtWidgets.QStackedWidget(self.scrollAreaWidgetContents)
        self.stackedWidget_3.setGeometry(QtCore.QRect(9, 360, 561, 51))
        self.stackedWidget_3.setObjectName("stackedWidget_3")
        self.new_save = QtWidgets.QWidget()
        self.new_save.setObjectName("new_save")
        self.discard = QtWidgets.QPushButton(self.new_save)
        self.discard.setGeometry(QtCore.QRect(370, 10, 75, 24))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.discard.sizePolicy().hasHeightForWidth())
        self.discard.setSizePolicy(sizePolicy)
        self.discard.setMaximumSize(QtCore.QSize(100, 16777215))
        self.discard.setStyleSheet("QPushButton{\n"
"  border: 1.5px solid black;\n"
"  border-radius: 12px;\n"
"  padding: 5px;\n"
"}\n"
"QPushButton:hover{\n"
"  background-color: rgb(213, 213, 213);  \n"
"}")
        self.discard.setObjectName("discard")
        self.reset = QtWidgets.QPushButton(self.new_save)
        self.reset.setGeometry(QtCore.QRect(470, 10, 75, 24))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.reset.sizePolicy().hasHeightForWidth())
        self.reset.setSizePolicy(sizePolicy)
        self.reset.setMaximumSize(QtCore.QSize(100, 16777215))
        self.reset.setStyleSheet("QPushButton{\n"
"  border: 1.5px solid black;\n"
"  border-radius: 12px;\n"
"  padding: 5px;\n"
"}\n"
"QPushButton:hover{\n"
"  background-color: rgb(213, 213, 213);  \n"
"}")
        self.reset.setObjectName("reset")
        self.label_14 = QtWidgets.QLabel(self.new_save)
        self.label_14.setGeometry(QtCore.QRect(90, 11, 51, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.save_btn = QtWidgets.QPushButton(self.new_save)
        self.save_btn.setGeometry(QtCore.QRect(1, 11, 75, 24))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.save_btn.sizePolicy().hasHeightForWidth())
        self.save_btn.setSizePolicy(sizePolicy)
        self.save_btn.setMaximumSize(QtCore.QSize(100, 16777215))
        self.save_btn.setStyleSheet("QPushButton{\n"
"  border: 1.5px solid black;\n"
"  border-radius: 12px;\n"
"  padding: 5px;\n"
"}\n"
"QPushButton:hover{\n"
"  background-color: rgb(213, 213, 213);  \n"
"}")
        self.save_btn.setObjectName("save_btn")
        self.comboBox = QtWidgets.QComboBox(self.new_save)
        self.comboBox.setGeometry(QtCore.QRect(150, 11, 181, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.stackedWidget_3.addWidget(self.new_save)
        self.edit_save = QtWidgets.QWidget()
        self.edit_save.setObjectName("edit_save")
        self.reset_2 = QtWidgets.QPushButton(self.edit_save)
        self.reset_2.setGeometry(QtCore.QRect(470, 10, 75, 24))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.reset_2.sizePolicy().hasHeightForWidth())
        self.reset_2.setSizePolicy(sizePolicy)
        self.reset_2.setMaximumSize(QtCore.QSize(100, 16777215))
        self.reset_2.setStyleSheet("QPushButton{\n"
"  border: 1.5px solid black;\n"
"  border-radius: 12px;\n"
"  padding: 5px;\n"
"}\n"
"QPushButton:hover{\n"
"  background-color: rgb(213, 213, 213);  \n"
"}")
        self.reset_2.setObjectName("reset_2")
        self.discard_2 = QtWidgets.QPushButton(self.edit_save)
        self.discard_2.setGeometry(QtCore.QRect(370, 10, 75, 24))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.discard_2.sizePolicy().hasHeightForWidth())
        self.discard_2.setSizePolicy(sizePolicy)
        self.discard_2.setMaximumSize(QtCore.QSize(100, 16777215))
        self.discard_2.setStyleSheet("QPushButton{\n"
"  border: 1.5px solid black;\n"
"  border-radius: 12px;\n"
"  padding: 5px;\n"
"}\n"
"QPushButton:hover{\n"
"  background-color: rgb(213, 213, 213);  \n"
"}")
        self.discard_2.setObjectName("discard_2")
        self.stackedWidget_4 = QtWidgets.QStackedWidget(self.edit_save)
        self.stackedWidget_4.setGeometry(QtCore.QRect(0, 4, 361, 31))
        self.stackedWidget_4.setObjectName("stackedWidget_4")
        self.page_10 = QtWidgets.QWidget()
        self.page_10.setObjectName("page_10")
        self.label_15 = QtWidgets.QLabel(self.page_10)
        self.label_15.setGeometry(QtCore.QRect(95, 13, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.save_btn_2 = QtWidgets.QPushButton(self.page_10)
        self.save_btn_2.setGeometry(QtCore.QRect(11, 6, 75, 24))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.save_btn_2.sizePolicy().hasHeightForWidth())
        self.save_btn_2.setSizePolicy(sizePolicy)
        self.save_btn_2.setMaximumSize(QtCore.QSize(100, 16777215))
        self.save_btn_2.setStyleSheet("QPushButton{\n"
"  border: 1.5px solid black;\n"
"  border-radius: 12px;\n"
"  padding: 5px;\n"
"}\n"
"QPushButton:hover{\n"
"  background-color: rgb(213, 213, 213);  \n"
"}")
        self.save_btn_2.setObjectName("save_btn_2")
        self.comboBox_2 = QtWidgets.QComboBox(self.page_10)
        self.comboBox_2.setGeometry(QtCore.QRect(160, 8, 181, 22))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.stackedWidget_4.addWidget(self.page_10)
        self.page_11 = QtWidgets.QWidget()
        self.page_11.setObjectName("page_11")
        self.save_btn_3 = QtWidgets.QPushButton(self.page_11)
        self.save_btn_3.setGeometry(QtCore.QRect(259, 6, 81, 24))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.save_btn_3.sizePolicy().hasHeightForWidth())
        self.save_btn_3.setSizePolicy(sizePolicy)
        self.save_btn_3.setMaximumSize(QtCore.QSize(100, 16777215))
        self.save_btn_3.setStyleSheet("QPushButton{\n"
"  border: 1.5px solid black;\n"
"  border-radius: 12px;\n"
"  padding: 5px;\n"
"}\n"
"QPushButton:hover{\n"
"  background-color: rgb(213, 213, 213);  \n"
"}")
        self.save_btn_3.setObjectName("save_btn_3")
        self.stackedWidget_4.addWidget(self.page_11)
        self.stackedWidget_3.addWidget(self.edit_save)
        self.stackedWidget_5 = QtWidgets.QStackedWidget(self.scrollAreaWidgetContents)
        self.stackedWidget_5.setGeometry(QtCore.QRect(490, 120, 31, 41))
        self.stackedWidget_5.setObjectName("stackedWidget_5")
        self.page_12 = QtWidgets.QWidget()
        self.page_12.setObjectName("page_12")
        self.pushButton_2 = QtWidgets.QPushButton(self.page_12)
        self.pushButton_2.setGeometry(QtCore.QRect(0, 10, 31, 24))
        self.pushButton_2.setStyleSheet("QPushButton{\n"
"  border: 1.5px solid black;\n"
"  border-radius: 12px;\n"
"  padding: 5px;\n"
"}\n"
"QPushButton:hover{\n"
"  background-color: rgb(213, 213, 213);  \n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.stackedWidget_5.addWidget(self.page_12)
        self.page_13 = QtWidgets.QWidget()
        self.page_13.setObjectName("page_13")
        self.stackedWidget_5.addWidget(self.page_13)
        self.stackedWidget_6 = QtWidgets.QStackedWidget(self.scrollAreaWidgetContents)
        self.stackedWidget_6.setGeometry(QtCore.QRect(490, 45, 31, 41))
        self.stackedWidget_6.setObjectName("stackedWidget_6")
        self.page_14 = QtWidgets.QWidget()
        self.page_14.setObjectName("page_14")
        self.pushButton_3 = QtWidgets.QPushButton(self.page_14)
        self.pushButton_3.setGeometry(QtCore.QRect(0, 10, 31, 24))
        self.pushButton_3.setStyleSheet("QPushButton{\n"
"  border: 1.5px solid black;\n"
"  border-radius: 12px;\n"
"  padding: 5px;\n"
"}\n"
"QPushButton:hover{\n"
"  background-color: rgb(213, 213, 213);  \n"
"}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.stackedWidget_6.addWidget(self.page_14)
        self.page_15 = QtWidgets.QWidget()
        self.page_15.setObjectName("page_15")
        self.stackedWidget_6.addWidget(self.page_15)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.stackedWidget.addWidget(self.page_2)
        self.stackedWidget_headr = QtWidgets.QStackedWidget(self.component)
        self.stackedWidget_headr.setGeometry(QtCore.QRect(0, 0, 251, 41))
        self.stackedWidget_headr.setObjectName("stackedWidget_headr")
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.label_4 = QtWidgets.QLabel(self.page_3)
        self.label_4.setGeometry(QtCore.QRect(50, 20, 49, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.stackedWidget_headr.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.label_5 = QtWidgets.QLabel(self.page_4)
        self.label_5.setGeometry(QtCore.QRect(50, 20, 49, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.stackedWidget_headr.addWidget(self.page_4)
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.label_6 = QtWidgets.QLabel(self.page_5)
        self.label_6.setGeometry(QtCore.QRect(40, 20, 71, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.stackedWidget_headr.addWidget(self.page_5)
        self.frame_5 = QtWidgets.QFrame(self.component)
        self.frame_5.setGeometry(QtCore.QRect(469, 0, 381, 71))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_5.sizePolicy().hasHeightForWidth())
        self.frame_5.setSizePolicy(sizePolicy)
        self.frame_5.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_5.setObjectName("frame_5")
        self.main_2 = QtWidgets.QPushButton(self.frame_5)
        self.main_2.setGeometry(QtCore.QRect(230, 10, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.main_2.setFont(font)
        self.main_2.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        self.main_2.setToolTip("Lock Vault")
        self.main_2.setToolTipDuration(-1)
        self.main_2.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.main_2.setStyleSheet("QPushButton{\n"
"  border: 1.5px solid black;\n"
"  border-radius: 15px;\n"
"  padding: 5px;\n"
"}\n"
"QPushButton:hover{\n"
"  background-color: rgb(213, 213, 213);  \n"
"}")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("../Data Manager/Project MEW/GUI INTERFACE/icons/lock.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.main_2.setIcon(icon6)
        self.main_2.setIconSize(QtCore.QSize(24, 24))
        self.main_2.setObjectName("main_2")
        self.stackedWidget_search = QtWidgets.QStackedWidget(self.component)
        self.stackedWidget_search.setGeometry(QtCore.QRect(370, 0, 181, 61))
        self.stackedWidget_search.setObjectName("stackedWidget_search")
        self.page_6 = QtWidgets.QWidget()
        self.page_6.setObjectName("page_6")
        self.lineEdit = QtWidgets.QLineEdit(self.page_6)
        self.lineEdit.setGeometry(QtCore.QRect(0, 20, 171, 21))
        self.lineEdit.setClearButtonEnabled(True)
        self.lineEdit.setObjectName("lineEdit")
        self.stackedWidget_search.addWidget(self.page_6)
        self.page_7 = QtWidgets.QWidget()
        self.page_7.setObjectName("page_7")
        self.stackedWidget_search.addWidget(self.page_7)
        self.verticalLayout.addWidget(self.Main)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.stackedWidget.setCurrentIndex(0)
        self.stackedWidget_2.setCurrentIndex(0)
        self.stackedWidget_3.setCurrentIndex(1)
        self.stackedWidget_4.setCurrentIndex(1)
        self.stackedWidget_5.setCurrentIndex(0)
        self.stackedWidget_6.setCurrentIndex(0)
        self.stackedWidget_headr.setCurrentIndex(1)
        self.stackedWidget_search.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.create_entry.setStatusTip(_translate("MainWindow", "Create New Entry"))
        self.passwordgen.setStatusTip(_translate("MainWindow", "Generate New Password"))
        self.passwordgen.setWhatsThis(_translate("MainWindow", "Generate Passwords"))
        self.passwordgen.setAccessibleName(_translate("MainWindow", "Generate Passwords"))
        self.passwordgen.setAccessibleDescription(_translate("MainWindow", "Generate Passwords"))
        self.label_2.setText(_translate("MainWindow", "New Entry"))
        self.create_folder.setStatusTip(_translate("MainWindow", "Create New Folder"))
        self.label_13.setText(_translate("MainWindow", "Create"))
        self.settings.setStatusTip(_translate("MainWindow", "Open Settings"))
        self.about.setStatusTip(_translate("MainWindow", "About Data Manager"))
        self.label_3.setText(_translate("MainWindow", "More"))
        self.vault_2.setStatusTip(_translate("MainWindow", "Open All Your Stored Data"))
        self.label.setText(_translate("MainWindow", "All Entries"))
        self.main.setStatusTip(_translate("MainWindow", "Open The Main Menu"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Entries), _translate("MainWindow", "Entries"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.FolderSelection), _translate("MainWindow", "Folder Selection"))
        self.label_8.setText(_translate("MainWindow", "Nothing Here, Create Something New?"))
        self.create_folder_2.setStatusTip(_translate("MainWindow", "Create New Folder"))
        self.passwordgen_2.setStatusTip(_translate("MainWindow", "Generate New Password"))
        self.passwordgen_2.setWhatsThis(_translate("MainWindow", "Generate Passwords"))
        self.passwordgen_2.setAccessibleName(_translate("MainWindow", "Generate Passwords"))
        self.passwordgen_2.setAccessibleDescription(_translate("MainWindow", "Generate Passwords"))
        self.create_entry_2.setStatusTip(_translate("MainWindow", "Create New Entry"))
        self.label_16.setText(_translate("MainWindow", "New Entry"))
        self.label_17.setText(_translate("MainWindow", "New Folder"))
        self.label_18.setText(_translate("MainWindow", "Generate Password"))
        self.label_9.setText(_translate("MainWindow", "Website Address:"))
        self.label_10.setText(_translate("MainWindow", "User Name:"))
        self.primary_websitedomain.setText(_translate("MainWindow", "Use this address as Primary Host Address."))
        self.lineEdit_2.setPlaceholderText(_translate("MainWindow", "Title"))
        self.label_11.setText(_translate("MainWindow", "Password:"))
        self.label_12.setText(_translate("MainWindow", "Notes:"))
        self.pushButton.setText(_translate("MainWindow", "C"))
        self.discard.setText(_translate("MainWindow", "Discard"))
        self.reset.setText(_translate("MainWindow", "Reset All"))
        self.label_14.setText(_translate("MainWindow", "In Folder"))
        self.save_btn.setText(_translate("MainWindow", "Save"))
        self.comboBox.setItemText(0, _translate("MainWindow", "No Folder"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Create A New Folder"))
        self.reset_2.setText(_translate("MainWindow", "Close"))
        self.discard_2.setText(_translate("MainWindow", "Delete"))
        self.label_15.setText(_translate("MainWindow", "To Folder"))
        self.save_btn_2.setText(_translate("MainWindow", "Save"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "No Folder"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "Create A New Folder"))
        self.save_btn_3.setText(_translate("MainWindow", "Edit"))
        self.pushButton_2.setText(_translate("MainWindow", "C"))
        self.pushButton_3.setText(_translate("MainWindow", "C"))
        self.label_4.setText(_translate("MainWindow", "Main"))
        self.label_5.setText(_translate("MainWindow", "Vault"))
        self.label_6.setText(_translate("MainWindow", "Settings"))
        self.main_2.setStatusTip(_translate("MainWindow", "Lock Vault"))
        self.main_2.setText(_translate("MainWindow", "Lock"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "Search Through You Entries"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
